[package]
name = "simple"
version = "0.2.0"
edition = "2024"

[dependencies]
egui = { version = "0.33.0", features = ["callstack"] }
eframe = { version = "0.33.0"}
egui_extras = "0.33.0"

egui_tool_windows = { path = "../.." }
shared = { path = "../shared" }

# logging
env_logger = "0.11.8"